import { Button, ThemeClient } from "@ginga-ui/core";
import { Geist, Geist_Mono } from "next/font/google";

import type { Metadata } from "next";

import "@ginga-ui/core/index.css";
import "@ginga-ui/core/variables.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeClient = new ThemeClient({
    clientType: "openai",
    apiKey: process.env.OPENAI_API_KEY!,
  });
  const { CSSCode } = await themeClient.generateTheme("fairy tale");

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <style>{CSSCode}</style>
        <Button>Click me</Button>
        {children}
      </body>
    </html>
  );
}
